version: '3.4'

services:

  vaultwarden:
    image: service:latest
    ports:
      - '127.0.0.1:8200:80'
    volumes:
      - service-data:/data
      - service-database:/database

  backup:
    image: adrienpoupa/rclone-backup:latest
    # environment:
    #   RCLONE_REMOTE_NAME: 'RcloneBackup'
    #   RCLONE_REMOTE_DIR: '/RcloneBackup/'
    #   RCLONE_GLOBAL_FLAG: ''
    #   CRON: '5 * * * *'
    #   BACKUP_FOLDER_NAME: 'data'
    #   BACKUP_FOLDER_PATH: '/data'
    #   DB_TYPE: 'sqlite'
    #   SQLITE_DATABASE: '/database/database.sqlite'
    #   ZIP_ENABLE: 'TRUE'
    #   ZIP_PASSWORD: '123456'
    #   ZIP_TYPE: 'zip'
    #   BACKUP_FILE_SUFFIX: '%Y%m%d'
    #   BACKUP_KEEP_DAYS: 0
    #   PING_URL: ''
    #   MAIL_SMTP_ENABLE: 'FALSE'
    #   MAIL_SMTP_VARIABLES: ''
    #   MAIL_TO: ''
    #   MAIL_WHEN_SUCCESS: 'TRUE'
    #   MAIL_WHEN_FAILURE: 'TRUE'
    #   TIMEZONE: 'UTC'
    volumes:
      - rclone-backup-data:/config

volumes:
  service-data:
  service-database:
  rclone-backup-data:
